name: PHPCS
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: First job
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: First step
        run: make lint